---

- block:

  - name: Download Oracle JDK rpm from url
    get_url: url={{oracle_jdk_download_url}} dest={{oracle_jdk_rpm_dest}}/{{oracle_jdk_rpm_filename}} headers={{oracle_jdk_download_url_headers}} force=yes

  - name: Installing Oracle JDK rpm
    yum: name={{oracle_jdk_rpm_dest}}/{{oracle_jdk_rpm_filename}} state=present update_cache=yes validate_certs=no
