---

- block:

# following sources were used to derive the minimal ansible tasks:
# https://github.com/nodesource/distributions/blob/master/rpm/setup_6.x
# https://github.com/geerlingguy/ansible-role-nodejs/blob/master/tasks/setup-RedHat.yml

  - name: Import Nodesource RPM key (CentOS 7+)
    rpm_key: key={{nodejs_rpm_key}} state=present

  # The repo url ends up being something like https://rpm.nodesource.com/pub_6.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
  - name: Add Nodesource repositories for Node.js (CentOS 7+)
    yum:
      name: https://rpm.nodesource.com/pub_{{nodejs_version}}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm
      state: present
      update_cache: yes

  - name: Installing nodejs and related packages
    yum: name={{ item }} update_cache=yes state=present
    with_items:
      - nodejs
