---

- include_vars: '{{mariadb_yml_file}}'

- block:

  - name: Install mariaDb packages
    yum:  name={{item}} state=installed update_cache=yes
    with_items: "{{ mariadb_packages }}"
    ignore_errors: yes
    when: mariadb_packages is defined
    register: package_install_result

  - name: Stop mariadb if packages marked for removal
    service: name=mariadb state=stopped
    when: mariadb_packages_old is defined

  - name: Remove mariaDb packages
    yum: name={{ item }} state=absent
    with_items: "{{ mariadb_packages_old }}"
    ignore_errors: yes
    when: mariadb_packages_old is defined

  - name: Update (MariaDB) MySQL root password for all root accounts 
    mysql_user:
      login_user: root
      check_implicit_admin: yes
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_pass }}"
      state: present
    with_items:
      - ::1
      - localhost
    when: mariadb_packages is defined and package_install_result.changed

  - name: Ensure Anonymous user(s) are not in the database
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_pass }}"
      name: ''
      host: "{{ item }}"
      state: absent
    with_items:
      - localhost
    when: mariadb_packages is defined and package_install_result.changed

  - name: Remove the test database
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_pass }}"
      name: test
      state: absent
    when: mariadb_packages is defined and package_install_result.changed
    notify:
      - Restart mariadb
