---

- include_vars: '{{percona_yml_file}}'

- block:

  - name: Install Percona Yum repository
    yum: name={{ percona_repository }} update_cache=yes state=present

  - name: Install Percona MySQL packages
    yum:  name={{item}} state=installed update_cache=yes
    with_items: "{{ mysql_packages }}"
    ignore_errors: yes
    when: mysql_packages is defined
    register: package_install_result
    notify:
      - Restart MySQL

  - name: Remove MySQL packages
    yum: name={{ item }} state=absent purge=yes
    with_items: "{{ mysql_packages_old }}"
    ignore_errors: yes
    when: mysql_packages_old is defined

  - name: Update MySQL root password for all root accounts 
    mysql_user:
      login_user: root
      check_implicit_admin: yes
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_pass }}"
      state: present
    with_items:
      - ::1
      - localhost
    when: mysql_packages is defined and package_install_result.changed

  - name: Ensure Anonymous user(s) are not in the database
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_pass }}"
      name: ''
      host: "{{ item }}"
      state: absent
    with_items:
      - localhost
    when: mysql_packages is defined

  - name: Remove the test database
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_pass }}"
      name: test
      state: absent
    when: mysql_packages is defined
    notify:
      - Restart MySQL
