---
- hosts: ansible-servers

# Note: ansible uses path of playbook as current working directory
  vars:
    users_json_file: ../vars/users.json
    apache_yml_file: ../vars/apache.yml
    mariadb_yml_file: ../vars/mariadb.yml
    php7_yml_file: ../vars/php7.yml
    percona_yml_file: ../vars/percona.yml

# Roles NOT yet updated for CentOS:
# elasticsearch
#
# FYI: Use percona as database, tends to work better with CentOS

  roles:
     - { role: common, tags: ['common', 'ci', 'developer'] }
     - { role: users, tags: ['users', 'developer'] }
     - { role: apache, tags: ['apache', 'apache2', 'developer'] }
#    we use percona for magento2 and middleware, so no need for mariadb       
#    - { role: mariadb, tags: ['mariadb', 'mariadb5.5'] }
     - { role: percona, tags: ['percona', 'percona5.6', 'developer'] }
     - { role: php7, tags: ['php', 'php7', 'developer'] }
     - { role: nodejs, tags: ['nodejs', 'npm', 'frontend'] }
     - { role: mailhog, tags: ['mailhog', 'local-smtp', 'ci', 'developer'] }
     - { role: java8, tags: ['java', 'java8', 'ci'] }
     - { role: supervisor, tags: ['supervisor', 'supervisord', 'ci', 'developer'] }
#    - { role: elasticsearch, tags: ['elasticsearch', 'elasticsearch-5.x'] }
     - { role: supervisor-mailhog, tags: ['mailhog.setup', 'ci', 'developer'] }
     - { role: memcached, tags: ['memcache', 'memcached', 'developer'] }
     - { role: varnish, tags: ['varnish', 'varnish5', 'developer'] }
     - { role: jenkins, tags: ['jenkins', 'ci'] }
