---

- include_vars: '{{php7_yml_file}}'

- block:

  - name: Installing PHP7 repository
    yum: name={{ php7_repository }} update_cache=yes state=present
    when: php7_repository is defined

  - name: Installing PHP7 packages
    yum: name={{ item }} update_cache=yes state=present
    with_items: "{{php7_packages}}"
    when: php7_packages is defined

  - name: Create php ini for CLI (does not exist by default for CentOS)
    shell: cp /etc/php.ini /etc/php-cli.ini -f
    when: php7_packages is defined
    
# Update PHP ini files
  - name: Updating php ini for cli
    lineinfile: dest=/etc/php-cli.ini
                regexp="{{ item.regexp }}"
                line="{{ item.line }}"
                state="{{ item.state | default('present') }}"
    with_items: '{{cli_ini}}'
    when: cli_ini is defined

  - name: Updating php ini for apache
    lineinfile: dest=/etc/php.ini
                regexp="{{ item.regexp }}"
                line="{{ item.line }}"
                state="{{ item.state | default('present') }}"
    with_items: '{{apache_ini}}'
    when: apache_ini is defined
    notify: restart apache2

# Due to how CentOS handles php ini files, we can't have separate xdebug.ini for CLI and Apache.
# Instead ini files for disabling and enabling xdebug are provided.
# Then you create symlink to one of them, with symlink name of /etc/php.d/xdebug.ini

# XDebug configuration

  - name: Creating disabled xdebug template ini
    template: src=xdebug.ini.disabled.j2 dest=/etc/php.d/xdebug-disabled.ini.dist owner=root group=root mode='u=rw,g=r,o=r'

  - name: Creating enabled xdebug template ini
    template: src=xdebug.ini.enabled.j2 dest=/etc/php.d/xdebug-enabled.ini.dist owner=root group=root mode='u=rw,g=r,o=r'

  - name: Enabling xdebug
    file: src=/etc/php.d/xdebug-enabled.ini.dist dest=/etc/php.d/xdebug.ini state=link force=yes
    when: xdebug_apache_enabled is defined and xdebug_apache_enabled == True

  - name: Disabling xdebug
    file: src=/etc/php.d/xdebug-disabled.ini.dist dest=/etc/php.d/xdebug.ini state=link force=yes
    when: xdebug_apache_enabled is defined and xdebug_apache_enabled == False
    notify: restart apache2

  - name: Adding helper scripts to user local bin
    template: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode='u=rwx,g=rx,o=rx'
    with_items:
        - 'enable-xdebug'
        - 'disable-xdebug'

# Security settings

  - name: Set selinux policy
    selinux: policy={{selinux_policy}} state={{selinux_state}}
    when: selinux_policy is defined and selinux_state is defined

  - name: Open firewall for xdebug
    firewalld: port={{remote_port}}/tcp state=enabled permanent=true
    when: xdebug_apache_enabled is defined and xdebug_apache_enabled == True
